"""index foreign keys for read performance

Revision ID: 1b6f01972811
Revises: b2fb236ba724
Create Date: 2026-09-18 08:40:45.106324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6f01972811'
down_revision = 'b2fb236ba724'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_problem_statement_id'), 'applications', ['problem_statement_id'], unique=False)
    op.create_index(op.f('ix_applications_startup_id'), 'applications', ['startup_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_checklist_items_application_id'), 'checklist_items', ['application_id'], unique=False)
    op.create_index('ix_coi_app_evaluator', 'coi_declarations', ['application_id', 'evaluator_id'], unique=False)
    op.create_index(op.f('ix_coi_declarations_application_id'), 'coi_declarations', ['application_id'], unique=False)
    op.create_index(op.f('ix_coi_declarations_evaluator_id'), 'coi_declarations', ['evaluator_id'], unique=False)
    op.create_index(op.f('ix_compliance_records_application_id'), 'compliance_records', ['application_id'], unique=False)
    op.create_index(op.f('ix_compliance_records_problem_statement_id'), 'compliance_records', ['problem_statement_id'], unique=False)
    op.create_index('ix_eval_scores_app_evaluator', 'evaluation_scores', ['application_id', 'evaluator_id'], unique=False)
    op.create_index(op.f('ix_evaluation_scores_application_id'), 'evaluation_scores', ['application_id'], unique=False)
    op.create_index(op.f('ix_evaluation_scores_evaluator_id'), 'evaluation_scores', ['evaluator_id'], unique=False)
    op.create_index(op.f('ix_evidence_milestone_id'), 'evidence', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_invites_problem_statement_id'), 'invites', ['problem_statement_id'], unique=False)
    op.create_index(op.f('ix_invites_startup_id'), 'invites', ['startup_id'], unique=False)
    op.create_index(op.f('ix_kpi_verdicts_contract_id'), 'kpi_verdicts', ['contract_id'], unique=False)
    op.create_index('ix_kpi_verdicts_kpi_contract', 'kpi_verdicts', ['kpi_id', 'contract_id'], unique=False)
    op.create_index(op.f('ix_kpi_verdicts_kpi_id'), 'kpi_verdicts', ['kpi_id'], unique=False)
    op.create_index(op.f('ix_kpis_problem_statement_id'), 'kpis', ['problem_statement_id'], unique=False)
    op.create_index(op.f('ix_pilot_milestones_contract_id'), 'pilot_milestones', ['contract_id'], unique=False)
    op.create_index(op.f('ix_problem_statements_officer_id'), 'problem_statements', ['officer_id'], unique=False)
    op.create_index(op.f('ix_ps_evaluator_assignments_evaluator_id'), 'ps_evaluator_assignments', ['evaluator_id'], unique=False)
    op.create_index(op.f('ix_ps_evaluator_assignments_problem_statement_id'), 'ps_evaluator_assignments', ['problem_statement_id'], unique=False)
    op.create_index('ix_ps_evaluator_ps_evaluator', 'ps_evaluator_assignments', ['problem_statement_id', 'evaluator_id'], unique=False)
    op.create_index(op.f('ix_risk_profiles_application_id'), 'risk_profiles', ['application_id'], unique=False)
    op.create_index(op.f('ix_selection_decisions_problem_statement_id'), 'selection_decisions', ['problem_statement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_selection_decisions_problem_statement_id'), table_name='selection_decisions')
    op.drop_index(op.f('ix_risk_profiles_application_id'), table_name='risk_profiles')
    op.drop_index('ix_ps_evaluator_ps_evaluator', table_name='ps_evaluator_assignments')
    op.drop_index(op.f('ix_ps_evaluator_assignments_problem_statement_id'), table_name='ps_evaluator_assignments')
    op.drop_index(op.f('ix_ps_evaluator_assignments_evaluator_id'), table_name='ps_evaluator_assignments')
    op.drop_index(op.f('ix_problem_statements_officer_id'), table_name='problem_statements')
    op.drop_index(op.f('ix_pilot_milestones_contract_id'), table_name='pilot_milestones')
    op.drop_index(op.f('ix_kpis_problem_statement_id'), table_name='kpis')
    op.drop_index(op.f('ix_kpi_verdicts_kpi_id'), table_name='kpi_verdicts')
    op.drop_index('ix_kpi_verdicts_kpi_contract', table_name='kpi_verdicts')
    op.drop_index(op.f('ix_kpi_verdicts_contract_id'), table_name='kpi_verdicts')
    op.drop_index(op.f('ix_invites_startup_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_problem_statement_id'), table_name='invites')
    op.drop_index(op.f('ix_evidence_milestone_id'), table_name='evidence')
    op.drop_index(op.f('ix_evaluation_scores_evaluator_id'), table_name='evaluation_scores')
    op.drop_index(op.f('ix_evaluation_scores_application_id'), table_name='evaluation_scores')
    op.drop_index('ix_eval_scores_app_evaluator', table_name='evaluation_scores')
    op.drop_index(op.f('ix_compliance_records_problem_statement_id'), table_name='compliance_records')
    op.drop_index(op.f('ix_compliance_records_application_id'), table_name='compliance_records')
    op.drop_index(op.f('ix_coi_declarations_evaluator_id'), table_name='coi_declarations')
    op.drop_index(op.f('ix_coi_declarations_application_id'), table_name='coi_declarations')
    op.drop_index('ix_coi_app_evaluator', table_name='coi_declarations')
    op.drop_index(op.f('ix_checklist_items_application_id'), table_name='checklist_items')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_applications_startup_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_problem_statement_id'), table_name='applications')
    # ### end Alembic commands ###
