"""initial schema - 24 tables, layers 1-5 + cross-cutting

Revision ID: b2fb236ba724
Revises: 
Create Date: 2026-09-06 10:19:51.733526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fb236ba724'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('healthcare', 'sanitation', 'transport', 'education', 'agriculture', 'governance', 'iot_hardware', name='categoryenum'), nullable=True),
    sa.Column('sensitivity_tag', sa.String(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubric_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('healthcare', 'sanitation', 'transport', 'education', 'agriculture', 'governance', 'iot_hardware', name='categoryenum'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('officer', 'startup', 'evaluator', 'independent_evaluator', 'admin', name='roleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('healthcare', 'sanitation', 'transport', 'education', 'agriculture', 'governance', 'iot_hardware', name='categoryenum'), nullable=False),
    sa.Column('target_beneficiaries', sa.String(), nullable=True),
    sa.Column('baseline', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('measurement_method', sa.String(), nullable=True),
    sa.Column('measurement_period', sa.String(), nullable=True),
    sa.Column('budget_range', sa.Enum('under_5L', 'band_5L_to_25L', 'band_25L_to_1Cr', 'over_1Cr', name='budgetrangeenum'), nullable=True),
    sa.Column('budget_description', sa.Text(), nullable=True),
    sa.Column('sensitivity_flags', sa.JSON(), nullable=True),
    sa.Column('success_condition', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'closed', name='psstatusenum'), nullable=False),
    sa.Column('additional_required_documents', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commercial_unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('startup_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('dpiit_number', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('gst', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('sector_tags', sa.JSON(), nullable=True),
    sa.Column('team_headcount', sa.Integer(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('trl_stage', sa.Integer(), nullable=True),
    sa.Column('architecture', sa.JSON(), nullable=True),
    sa.Column('api_available', sa.Boolean(), nullable=True),
    sa.Column('past_deployments', sa.JSON(), nullable=True),
    sa.Column('funding_band', sa.Enum('bootstrapped', 'pre_seed', 'seed', 'series_a', 'series_b_plus', name='fundingbandenum'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dpiit_status', sa.Enum('unverified', 'verified', 'failed', name='dpiitstatusenum'), nullable=False),
    sa.Column('entity_verified', sa.Boolean(), nullable=False),
    sa.Column('pan_verified', sa.Boolean(), nullable=False),
    sa.Column('gst_verified', sa.Boolean(), nullable=False),
    sa.Column('compliance_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_verified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compliance_verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_statement_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('technical_proposal', sa.JSON(), nullable=True),
    sa.Column('commercial_proposal', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('applied', 'under_review', 'under_evaluation', 'selected', 'not_selected', 'contracted', 'completed', name='applicationstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_statement_id'], ['problem_statements.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_statement_id', 'startup_id', name='uq_application_ps_startup')
    )
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_statement_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_statement_id'], ['problem_statements.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_statement_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('baseline', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('measurement_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['problem_statement_id'], ['problem_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ps_evaluator_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_statement_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problem_statement_id'], ['problem_statements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_statement_id', 'evaluator_id', name='uq_ps_evaluator')
    )
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'uploaded', 'verified', 'rejected', name='checkliststatusenum'), nullable=False),
    sa.Column('file_reference', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coi_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('declared_conflict', sa.Boolean(), nullable=False),
    sa.Column('recused', sa.Boolean(), nullable=False),
    sa.Column('declared_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'evaluator_id', name='uq_coi_app_eval')
    )
    op.create_table('compliance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_statement_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problem_statement_id'], ['problem_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('containment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('max_scope', sa.Text(), nullable=True),
    sa.Column('max_financial_exposure', sa.String(), nullable=True),
    sa.Column('fallback_process', sa.Text(), nullable=True),
    sa.Column('data_terms', sa.Text(), nullable=True),
    sa.Column('exit_conditions', sa.Text(), nullable=True),
    sa.Column('support_obligations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('clause_snapshot', sa.JSON(), nullable=False),
    sa.Column('initiated_by', sa.Integer(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('eligibility_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('dpiit_verified', sa.Enum('pass_', 'fail', 'needs_clarification', name='passfailncenum'), nullable=True),
    sa.Column('entity_valid', sa.Enum('pass_', 'fail', 'needs_clarification', name='passfailncenum'), nullable=True),
    sa.Column('pan_gst_present', sa.Enum('pass_', 'fail', name='pangstenum'), nullable=True),
    sa.Column('certification_check', sa.Enum('pass_', 'fail', 'needs_clarification', 'not_applicable', name='certificationcheckenum'), nullable=True),
    sa.Column('sector_eligible', sa.Enum('pass_', 'fail', 'needs_clarification', name='passfailncenum'), nullable=True),
    sa.Column('overall_result', sa.Enum('eligible', 'not_eligible', 'needs_clarification', name='overalleligibilityenum'), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('evaluation_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['criterion_id'], ['rubric_criteria.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'evaluator_id', 'criterion_id', name='uq_score_app_eval_criterion')
    )
    op.create_table('risk_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('technical_risk', sa.Enum('low', 'medium', 'high', name='risklevelenum'), nullable=False),
    sa.Column('financial_risk', sa.Enum('low', 'medium', 'high', name='risklevelenum'), nullable=False),
    sa.Column('implementation_risk', sa.Enum('low', 'medium', 'high', name='risklevelenum'), nullable=False),
    sa.Column('cybersecurity_risk', sa.Enum('low', 'medium', 'high', name='risklevelenum'), nullable=False),
    sa.Column('data_risk', sa.Enum('low', 'medium', 'high', name='risklevelenum'), nullable=False),
    sa.Column('scalability_risk', sa.Enum('low', 'medium', 'high', name='risklevelenum'), nullable=False),
    sa.Column('overall_risk', sa.Enum('low', 'medium', 'high', name='risklevelenum'), nullable=False),
    sa.Column('stage', sa.Enum('preliminary', 'final', name='riskstageenum'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandbox_trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('functional_check', sa.Enum('pass_', 'fail', name='sandboxcheckenum'), nullable=True),
    sa.Column('directional_kpi_check', sa.Enum('pass_', 'fail', name='sandboxcheckenum'), nullable=True),
    sa.Column('operational_fit_check', sa.Enum('pass_', 'fail', name='sandboxcheckenum'), nullable=True),
    sa.Column('no_red_flags_check', sa.Enum('pass_', 'fail', name='sandboxcheckenum'), nullable=True),
    sa.Column('verdict', sa.Enum('promising', 'not_promising', 'inconclusive', name='sandboxverdictenum'), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verification_mode', sa.Enum('desk_review', 'field_visit', name='verificationmodeenum'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('selection_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_statement_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problem_statement_id'], ['problem_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Enum('met', 'not_met', name='kpiverdictresultenum'), nullable=False),
    sa.Column('verification_mode', sa.Enum('desk_review', 'field_visit', name='verificationmodeenum'), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('milestone_type', sa.Enum('deployment', 'field_testing', 'outcome_measurement', 'independent_verification', 'final_decision', name='milestonetypeenum'), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'submitted', 'accepted', 'rejected', name='milestonestatusenum'), nullable=False),
    sa.Column('payment_status', sa.Enum('not_due', 'due', 'paid', name='paymentstatusenum'), nullable=False),
    sa.Column('target_value', sa.String(), nullable=True),
    sa.Column('target_unit', sa.String(), nullable=True),
    sa.Column('submitted_value', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('overall_result', sa.Enum('scale', 'iterate', 'stop', name='pilotoutcomeresultenum'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('source_tag', sa.Enum('startup_submitted', 'govt_data', 'field_visit', name='evidencesourceenum'), nullable=False),
    sa.Column('file_reference', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['pilot_milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_table('pilot_outcomes')
    op.drop_table('pilot_milestones')
    op.drop_table('kpi_verdicts')
    op.drop_table('selection_decisions')
    op.drop_table('sandbox_trials')
    op.drop_table('risk_profiles')
    op.drop_table('evaluation_scores')
    op.drop_table('eligibility_checks')
    op.drop_table('contracts')
    op.drop_table('containment_plans')
    op.drop_table('compliance_records')
    op.drop_table('coi_declarations')
    op.drop_table('checklist_items')
    op.drop_table('ps_evaluator_assignments')
    op.drop_table('kpis')
    op.drop_table('invites')
    op.drop_table('applications')
    op.drop_table('startup_profiles')
    op.drop_table('problem_statements')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('rubric_criteria')
    op.drop_table('checklist_rules')
    # ### end Alembic commands ###
